[package]
name = "lfsx-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
lfsx-server = { path = "../server", features = ["fuzzing"] }

[[bin]]
name = "codec"
path = "fuzz_targets/codec.rs"
test = false
doc = false
bench = false

[[bin]]
name = "keys"
path = "fuzz_targets/keys.rs"
test = false
doc = false
bench = false

[[bin]]
name = "range"
path = "fuzz_targets/range.rs"
test = false
doc = false
bench = false

[[bin]]
name = "seed"
path = "seed.rs"
test = false
doc = false
bench = false
