[package]
name = "lfsx-server"
version = "1.16.5"
description = "A fast, lightweight, secure Git LFS server"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage = "https://lfsx.dev"
documentation = "https://lfsx.dev/docs/quickstart"
readme = "README.md"
keywords = ["git", "git-lfs", "lfs", "server", "self-hosted"]
categories = ["command-line-utilities", "development-tools", "web-programming::http-server"]
exclude = ["tests/", "examples/"]

[features]
fuzzing = []

[dependencies]
axum.workspace = true
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
rustls.workspace = true
base64.workspace = true
time.workspace = true
prometheus.workspace = true
sha2.workspace = true
hex.workspace = true
futures-util.workspace = true
zstd.workspace = true
chacha20poly1305.workspace = true
blake3.workspace = true
getrandom.workspace = true
rusty-s3.workspace = true
thiserror.workspace = true
jsonwebtoken.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
tempfile = "3"
rsa = "0.9"
rand_core = { version = "0.6", features = ["getrandom"] }
