name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@b4d7dddc7936e751d1d292c34f09d392cf0d4164 # main
    with:
      runner: ubuntu-latest
    secrets: inherit
